### ISSUE TITLE
Proper addon repository?

### ISSUE THREAD

**Issue by romanvm** [thetvdb/kodi#1]
As I said on the Kodi forum, installing addons via URLs is a hack and not officially supported. You need to create a custom addon repo (it can be any static files hosting including GH) and a special [repo addon ](https://kodi.wiki/view/Add-on_repositories). Also with a proper repository you will have addon auto-updates working correctly.

**Comment by antheaezzell** [comment]
As this is related to the older scraper, I am going to close this issue @romanvm
